services:
  consul:
    image: hashicorp/consul:latest
    ports:
      - "8500:8500"
    environment:
      - CONSUL_BIND_INTERFACE=eth0
    networks:
      - notification_system
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.5"
          memory: "256M"

  notification:
    image: notification:v1
    ports:
      - "5275:80"
    networks:
      - notification_system
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.6"
          memory: "150M"
      restart_policy:
        condition: on-failure
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
    depends_on:
      - rabbitmq
      - consul
      - kafka
    hostname: notification
    
  notigw:
    image: notigw:v1
    ports:
      - "5282:80"
    networks:
      - notification_system
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.6"
          memory: "150M"
      restart_policy:
        condition: on-failure
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
    depends_on:
      - consul
      - rabbitmq
    hostname: notigw

  rabbitmq:
    image: rabbitmq:management
    hostname: rabbitmq
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - notification_system

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "sasa@123"
    ports:
      - "11433:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql
    networks:
      - notification_system
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  seq:
    image: datalust/seq:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    hostname: seq
    ports:
      - "5341:80"
    environment:
      - ACCEPT_EULA=Y
    volumes:
      - seq-data:/data
    networks:
      - notification_system
 
  portainer:
    image: portainer/portainer-ce
    ports:
      - "9000:9000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "portainer_data:/data"
    networks:
      - notification_system
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    restart: always
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    deploy:
      replicas: 1
      restart_policy:
        condition: any

  kafka:
    image: confluentinc/cp-kafka:latest
    restart: always
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:29092
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:29092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    deploy:
      replicas: 1
      restart_policy:
        condition: any

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    restart: always
    depends_on:
      - kafka
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
    deploy:
      replicas: 1
      restart_policy:
        condition: any

networks:
  notification_system:
    external: true

volumes:
  seq-data:
  sqlserverdata:
  portainer_data: