<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
		<Content Remove="C:\Users\USER\.nuget\packages\ppm.ocelot\1.0.5\contentFiles\any\net8.0\ocelot.Development.json" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Ocelot" Version="23.4.3" />
		<PackageReference Include="Ocelot.Provider.Consul" Version="23.0.0" />
		<PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
		<PackageReference Include="Consul" Version="1.7.14.7" />
	</ItemGroup>

</Project>
